insert into teams (id, name, group_name, flag_url) values
  ('A1', 'Mexico', 'Group A', 'https://flagcdn.com/w80/mx.png'),
  ('A2', 'Canada', 'Group A', 'https://flagcdn.com/w80/ca.png'),
  ('A3', 'Costa Rica', 'Group A', 'https://flagcdn.com/w80/cr.png'),
  ('A4', 'Jamaica', 'Group A', 'https://flagcdn.com/w80/jm.png'),
  ('B1', 'United States', 'Group B', 'https://flagcdn.com/w80/us.png'),
  ('B2', 'Panama', 'Group B', 'https://flagcdn.com/w80/pa.png'),
  ('B3', 'Honduras', 'Group B', 'https://flagcdn.com/w80/hn.png'),
  ('B4', 'Saudi Arabia', 'Group B', 'https://flagcdn.com/w80/sa.png'),
  ('C1', 'Brazil', 'Group C', 'https://flagcdn.com/w80/br.png'),
  ('C2', 'Colombia', 'Group C', 'https://flagcdn.com/w80/co.png'),
  ('C3', 'Ecuador', 'Group C', 'https://flagcdn.com/w80/ec.png'),
  ('C4', 'Peru', 'Group C', 'https://flagcdn.com/w80/pe.png'),
  ('D1', 'Argentina', 'Group D', 'https://flagcdn.com/w80/ar.png'),
  ('D2', 'Uruguay', 'Group D', 'https://flagcdn.com/w80/uy.png'),
  ('D3', 'Chile', 'Group D', 'https://flagcdn.com/w80/cl.png'),
  ('D4', 'Paraguay', 'Group D', 'https://flagcdn.com/w80/py.png'),
  ('E1', 'England', 'Group E', 'https://flagcdn.com/w80/gb.png'),
  ('E2', 'Netherlands', 'Group E', 'https://flagcdn.com/w80/nl.png'),
  ('E3', 'Denmark', 'Group E', 'https://flagcdn.com/w80/dk.png'),
  ('E4', 'Norway', 'Group E', 'https://flagcdn.com/w80/no.png'),
  ('F1', 'France', 'Group F', 'https://flagcdn.com/w80/fr.png'),
  ('F2', 'Belgium', 'Group F', 'https://flagcdn.com/w80/be.png'),
  ('F3', 'Switzerland', 'Group F', 'https://flagcdn.com/w80/ch.png'),
  ('F4', 'Austria', 'Group F', 'https://flagcdn.com/w80/at.png'),
  ('G1', 'Germany', 'Group G', 'https://flagcdn.com/w80/de.png'),
  ('G2', 'Italy', 'Group G', 'https://flagcdn.com/w80/it.png'),
  ('G3', 'Croatia', 'Group G', 'https://flagcdn.com/w80/hr.png'),
  ('G4', 'Serbia', 'Group G', 'https://flagcdn.com/w80/rs.png'),
  ('H1', 'Spain', 'Group H', 'https://flagcdn.com/w80/es.png'),
  ('H2', 'Portugal', 'Group H', 'https://flagcdn.com/w80/pt.png'),
  ('H3', 'Poland', 'Group H', 'https://flagcdn.com/w80/pl.png'),
  ('H4', 'Sweden', 'Group H', 'https://flagcdn.com/w80/se.png'),
  ('I1', 'Japan', 'Group I', 'https://flagcdn.com/w80/jp.png'),
  ('I2', 'South Korea', 'Group I', 'https://flagcdn.com/w80/kr.png'),
  ('I3', 'Australia', 'Group I', 'https://flagcdn.com/w80/au.png'),
  ('I4', 'Iran', 'Group I', 'https://flagcdn.com/w80/ir.png'),
  ('J1', 'Morocco', 'Group J', 'https://flagcdn.com/w80/ma.png'),
  ('J2', 'Senegal', 'Group J', 'https://flagcdn.com/w80/sn.png'),
  ('J3', 'Egypt', 'Group J', 'https://flagcdn.com/w80/eg.png'),
  ('J4', 'Tunisia', 'Group J', 'https://flagcdn.com/w80/tn.png'),
  ('K1', 'Nigeria', 'Group K', 'https://flagcdn.com/w80/ng.png'),
  ('K2', 'Cameroon', 'Group K', 'https://flagcdn.com/w80/cm.png'),
  ('K3', 'Algeria', 'Group K', 'https://flagcdn.com/w80/dz.png'),
  ('K4', 'Ivory Coast', 'Group K', 'https://flagcdn.com/w80/ci.png'),
  ('L1', 'Turkey', 'Group L', 'https://flagcdn.com/w80/tr.png'),
  ('L2', 'Ukraine', 'Group L', 'https://flagcdn.com/w80/ua.png'),
  ('L3', 'Czechia', 'Group L', 'https://flagcdn.com/w80/cz.png'),
  ('L4', 'Greece', 'Group L', 'https://flagcdn.com/w80/gr.png')
on conflict (id) do update set
  name = excluded.name,
  group_name = excluded.group_name,
  flag_url = excluded.flag_url;
